### ISSUE TITLE
Clicking away a UI dialog can sometimes produce an error.

### ISSUE THREAD

**Issue by Lemonymous** [kartoFlane/ITB-ModLoader#102]
Clicking away a dialog can sometimes produce this error:
`./scripts/mod_loader/ui/widgets/root.lua:58: Unable to set focus, because the UI element has no parent`

I have so far only seen it happen when clicking next to the Mod Configuration dialog to close it.

**Comment by Lemonymous** [comment]
`./scripts/mod_loader/ui/widgets/root.lua:255: in function 'event'` has this code:
```
self:setfocus(self.hoveredchild)
```
I find it likely that this is happening do a hovered element that was just detached, thus no longer having a parent.
It could possibly have the same root cause as #100

**Comment by kartoFlane** [comment]
Mitigated in #117
