### ISSUE TITLE
A ui element can recieve mousedown/up calls multiple times from the same single mousedown/up event.

### ISSUE THREAD

**Issue by Lemonymous** [kartoFlane/ITB-ModLoader#108]
On mousedown/up event, the hovered element will have mousedown/up called directly.

If that element does not consume the event by returning `true` in mousedown/up, the event will be passed through ui elements under the cursor; and can eventually end up calling mousedown/up on the hovered element yet again.

This double calling can cause a mess of things. See #100

**Comment by kartoFlane** [comment]
Fixed in #117
