### ISSUE TITLE
modUI does not update when changing resolution.

### ISSUE THREAD

**Issue by Lemonymous** [kartoFlane/ITB-ModLoader#18]
The issue is for the most part described in the title, but in order to show - not tell, here is how you can see what I mean for yourself:

in `ui/decorations/decoration.lua`, change the color of transparency to something clearly visible like this green tint.
```lua
deco.colors.transparent = sdl.rgba(0, 255, 0, 20)
```

in `modui/hangar.lua`, add decoration to the holder with this new transparent color.
```lua
local function createUi(root)
	local holder = Ui()
		:decorate({ DecoSolid(deco.colors.transparent) })
		:width(1):height(1)
		:addTo(root)
```

Now, go through the following steps.
1. Launch game. (if in windowed mode already, go to 4)
2. Change to windowed mode.
3. Exit game.
4. Change to fullscreen mode.
5. Enter the hangar with the `New Game` button.
6. If everything was done exactly, the green overlay should be offset from the full screen.

I remember having this issue in my Hotseat mod, and solving it by giving my UI elements an `update` function that would be called whenever the resolution (or other manually defined states) would change. You can see it in `Hotseat/scripts/ui/Ui2`.

I am sure you will want to find your own solution though.

**Comment by kartoFlane** [comment]
Thanks for letting me know, fixed in 0083061.

A better fix would be to have the UI root created by the mod loader take care of resizing its children, but after a brief look it seems like it'll be slightly more work to get it done without breaking anything else in the process.
