### ISSUE TITLE
how to load mod on mac?

### ISSUE THREAD

**Issue by Ronnoc** [kartoFlane/ITB-ModLoader#20]
or how to compile

**Comment by kartoFlane** [comment]
While lua itself is cross-platform, some important parts of the mod loader utilize DLLs that only work on Windows. As such, the mod loader does not "natively" work on Mac/Linux.

[User Nevyn87 over at ITB Discord managed to get it to work](https://discordapp.com/channels/417639520507527189/434468424173748224/715124277485109258) via some combination of Play on Mac (which is basically Wine, as far as I understand) and a few other tricks / settings adjustments, but I don't think he ever compiled an easy-to-follow guide on how to do it.
