### ISSUE TITLE
"attempt to index a nil global-"

### ISSUE THREAD

**Issue by LTSteve** [kartoFlane/ITB-ModLoader#3]
The game throws this error at line 103 of spawner_backend.lua, this happens after the victory screen. It's weird because I'm pretty sure modloader doesn't change this script at all, but i was able to get the error to stop by changing line 98 from "if Board == NULL then" to "if Board == nil then". No idea why this works (in fact it probably doesn't and just breaks the game somewhere else I haven't found yet)

**Comment by kartoFlane** [comment]
Thanks for letting me know -- I've encountered this problem during development and used the same fix you suggested, and promptly forgot about the problem. It seems that this fix works well enough as a bandaid, until I figure out why the spawner is being called when it shouldn't.

**Comment by kartoFlane** [comment]
Fixed in [v2.3.4](https://github.com/kartoFlane/ITB-ModLoader/releases/tag/v2.3.4)
