### ISSUE TITLE
Running selected tests in Testing Console

### ISSUE THREAD

**Issue by Lemonymous** [kartoFlane/ITB-ModLoader#49]
When using the test Testing Console available in Test Mech with `modApi.developmentMode = true`:

Running a subset of all tests can be a bit cumbersome. Unchecking Root Testsuite; checking only applicable tests, and clicking `Run Selected`, will currently not run any tests, because `Root Testsuite` remains unchecked.

To run selected tests, `Root Testsuite` must be checked (enabling all tests), and then undesired tests must all be unchecked in order to run selected tests.

**Comment by kartoFlane** [comment]
Right, that *does* sound very cumbersome, and it never occurred to me for some reason... I've pushed a branch with reworked testing logic, let me know if you have other suggestions for improvements (or if I accidentally broke something).

One notable change, to run tests via lua console you now have to type:
```lua
Tests.Runner:RunAllTests()
-- or
Tests.Runner:RunAllTests(Testsuites.name_of_testsuite)
```

**Comment by kartoFlane** [comment]
Rebased `feature/testing-console-improvements` onto `master`

**Comment by Lemonymous** [comment]
I am sure I am doing something incorrectly.
I tried `Tests.Runner:RunAllTests()`
and `Tests.Runner:RunAllTests(Testsuites.pawn)`

In both instances I get this error:
`./scripts/mod_loader/tests/test_runner.lua:24: attempt to index field 'onStatusChanged' (a nil value)`

**Comment by kartoFlane** [comment]
Right, there were some loose ends I forgot to tie up last night. The command I posted is also slightly incorrect, it should be: `Tests.Runner():RunAllTests()`
