### ISSUE TITLE
Differing scancode for enter on keypad

### ISSUE THREAD

**Issue by Lemonymous** [kartoFlane/ITB-ModLoader#73]
If I press [shift] + [keypad enter] with the console open, the mod loader doesn't think the console has been closed on my system.
Not sure if the scancode for [keypad enter] is different on our systems. There is another value among the scancode entries in the mod loader, that corresponds to my [keypad enter]. Is the RETURN2 entry an error, or are there different scancodes for different keyboard layouts?

My results:
```
SDLKeycodes.RETURN = 0xd
SDLKeycodes.RETURN2 = 0x4000009e
SDLKeycodes.KP_ENTER = 0x40000058
Enter on my keypad = 0x40000058
```

**Comment by kartoFlane** [comment]
No, you're right - `SDLKeycodes.KP_ENTER` is the keycode that corresponds to keypad enter. It's just not accounted for in code that checks if Enter key is  pressed, even though I thought I included it...
