### ISSUE TITLE
GetCurrentMission can return a mission after the mission has been completed

### ISSUE THREAD

**Issue by Lemonymous** [kartoFlane/ITB-ModLoader#83]
`GetCurrentMission` will return a mission table even when there is no current mission by executing the following steps:
- win a mission.
- while the mission has been completed, but not yet returned to the island view, exit to the main menu.
- load the game back up to return to the mission's end screen. This seems skip past the code that would clear the current mission variable (by design it appears in the code).
- `GetCurrentMission` will now be in a state where it will return this mission until either a new mission has been started, or exiting to the main menu again.

If the game is not exited while the mission is in the process of ending; `GetCurrentMission` will stop returning the current mission when the board stops being `busy`. It looks like this is by design, but I don't know for what reason.

RegionData.iBattleRegion appears to reflect the current mission more accurately than the current implementation of `GetCurrentMission`. RegionData.iBattleRegion does however, keep returning the mission for the full duration of the end mission screen, and until the player gains control to select a new mission on the current island. This is also the exact point in time where exiting to the main menu and returning to the game, will no longer return to the end mission screen for that mission.

**Comment by kartoFlane** [comment]
Resolved in #84
