### ISSUE TITLE
Crash when hovering over achievement toast, while it's about to disappear

### ISSUE THREAD

**Issue by kartoFlane** [kartoFlane/ITB-ModLoader#88]
Crash happens most likely due to this line:

https://github.com/kartoFlane/ITB-ModLoader/blob/f2387a1e48003c75cfa45ae4b54fe99807fad416/scripts/mod_loader/modui/toast.lua#L128

Most likely, the toast element gets detached, then the root element attempts to update the tooltip on the last hovered element (the detached toast), and crashes, since toast has `self.root` set to nil

**Comment by Lemonymous** [comment]
This should be fixed in PR #91
