### ISSUE TITLE
Palette selection UI doesn't show lock icon

### ISSUE THREAD

**Issue by kartoFlane** [kartoFlane/ITB-ModLoader#89]
Bug introduced here? https://github.com/kartoFlane/ITB-ModLoader/commit/e709a5ff315ec8ac114ebc6a08c1ba4c60a39ee6

**Comment by Lemonymous** [comment]
Yes, I believe I have a fix for it.

**Comment by Lemonymous** [comment]
It was only a visual glitch.
#90 should fix the issue.
