### ISSUE TITLE
Changes to palettes order sometimes don't stick, even despite game restarts

### ISSUE THREAD

**Issue by kartoFlane** [kartoFlane/ITB-ModLoader#99]
Happens for some people, but works fine for others. Unsure what the cause is yet.

Changes don't get saved at all, upon restarting the game and entering the palette arrange window, the palettes are reset to the old order.

Possibly caused by profile-based configuration being enabled?

**Comment by Lemonymous** [comment]
Confirmed: profile-based configuration enabled makes palettes not stick.
